
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  producer-api:
    build: 
      context: .
      dockerfile: ./apps/producer-api/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq

  worker:
    build: 
      context: .
      dockerfile: ./apps/worker/Dockerfile
    depends_on:
      - rabbitmq