apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: producer-api
  template:
    metadata:
      labels:
        app: producer-api
    spec:
      containers:
        - name: producer-api
          image: kaduzera/producer-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"