apiVersion: v1
kind: Service
metadata:
  name: producer-api
spec:
  selector:
    app: producer-api
  ports:
    - name: producer-api
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer