name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [producer-api, worker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (root)
        run: npm install

      - name: Build app (${{ matrix.app }})
        run: npm run build --project ${{ matrix.app }}

      - name: Lint app (${{ matrix.app }})
        run: npm run lint --project ${{ matrix.app }}

      - name: Build Docker image (${{ matrix.app }})
        run: |
          docker build -t ${{ matrix.app }}:${{ github.sha }} ./${{ matrix.app }}